name: Documentation

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build documentation
      run: |
        cargo doc --no-deps --all-features --document-private-items
        echo '<meta http-equiv="refresh" content="0; url=canva_connect">' > target/doc/index.html
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'target/doc'
        
    - name: Create docs archive for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd target/doc
        tar -czf ../../canva-connect-docs-${{ github.ref_name }}.tar.gz *
        
    - name: Upload docs to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: canva-connect-docs-${{ github.ref_name }}.tar.gz
        body: |
          ## Documentation
          
          📚 **View online**: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          
          📦 **Download**: The documentation is also available as a downloadable archive below.
          
          The documentation includes:
          - Complete API reference
          - Usage examples  
          - Internal implementation details
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
